# Generated by Django 3.0.6 on 2020-06-14 11:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_auto_20200602_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktranslation',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Text'),
        ),
    ]
