# Generated by Django 3.0.6 on 2020-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_auto_20200614_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Fragment',
                     'verbose_name_plural': 'Fragments'},
        ),
        migrations.AlterModelOptions(
            name='blocktranslation',
            options={'default_permissions': (), 'managed': True,
                     'verbose_name': 'Fragment Translation'},
        ),
        migrations.AlterField(
            model_name='block',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='block',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
