# Generated by Django 3.0.6 on 2020-06-16 10:41

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_auto_20200614_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='blocks'),
        ),
    ]
