# Generated by Django 3.0.6 on 2020-06-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_auto_20200616_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, upload_to='blocks'),
        ),
    ]
