# Generated by Django 3.0.6 on 2020-06-17 04:40

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_auto_20200616_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerField(blank=True, upload_to='blocks'),
        ),
    ]
