# Generated by Django 3.0.6 on 2020-06-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200619_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='promote',
            field=models.BooleanField(default=False, verbose_name='Promote'),
        ),
    ]
