# Generated by Django 3.0.6 on 2020-06-02 08:15

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('ordering', models.PositiveIntegerField(
                    default=0, verbose_name='Ordering')),
            ],
            options={
                'ordering': ['ordering'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SlideTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(
                    db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True,
                                                                on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hero.Slide')),
            ],
            options={
                'verbose_name': 'slide Translation',
                'db_table': 'hero_slide_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
