# Generated by Django 3.0.6 on 2020-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': [
                'ordering'], 'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterModelOptions(
            name='slidetranslation',
            options={'default_permissions': (), 'managed': True,
                     'verbose_name': 'Slide Translation'},
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(
                blank=True, upload_to='blocks', verbose_name='Image'),
        ),
    ]
