# Generated by Django 3.0.6 on 2020-06-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_auto_20200619_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidetranslation',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
    ]
