# Generated by Django 3.0.6 on 2020-06-02 10:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='events')),
                ('date_start', models.DateField(verbose_name='Date start')),
                ('date_end', models.DateField(blank=True, verbose_name='Date end')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordering')),
                ('artworks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.Artwork')),
            ],
            options={
                'ordering': ['ordering'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='related')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordering')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.Event')),
            ],
            options={
                'ordering': ['ordering', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Text')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='events.Event')),
            ],
            options={
                'verbose_name': 'event Translation',
                'db_table': 'events_event_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
