# Generated by Django 3.0.6 on 2020-06-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artworks',
        ),
        migrations.AddField(
            model_name='event',
            name='artworks',
            field=models.ManyToManyField(
                blank=True, null=True, to='gallery.Artwork'),
        ),
    ]
