# Generated by Django 3.0.6 on 2020-06-14 11:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200603_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtranslation',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text'),
        ),
    ]
