# Generated by Django 3.0.6 on 2020-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200614_1422'),
        ('events', '0005_auto_20200614_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': [
                'ordering'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventtranslation',
            options={'default_permissions': (), 'managed': True,
                     'verbose_name': 'Event Translation'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['ordering', '-created'],
                     'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterField(
            model_name='event',
            name='artworks',
            field=models.ManyToManyField(
                blank=True, to='gallery.Artwork', verbose_name='Artworks'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='related', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
