# Generated by Django 3.0.6 on 2020-06-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='target',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='merch.Product'),
        ),
    ]
