# Generated by Django 3.0.6 on 2020-06-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_auto_20200605_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
