# Generated by Django 3.0.6 on 2020-06-14 14:22

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_auto_20200614_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['ordering', '-created'],
                     'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': [
                'ordering'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='producttranslation',
            options={'default_permissions': (), 'managed': True,
                     'verbose_name': 'Product Translation'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': [
                'ordering'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tagtranslation',
            options={'default_permissions': (), 'managed': True,
                     'verbose_name': 'Tag Translation'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='related', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='gallery', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(
                blank=True, to='merch.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
